/**
 * @author Anthony Altieri on 11/15/16.
 */


// Questions
const QUESTION_ASKED = 'QUESTION_ASKED';
const QUESTION_REMOVED = 'QUESTION_REMOVED';
const ADD_VOTE = 'VOTE_ADD';
const REMOVE_VOTE = 'REMOVE_VOTE';
const ADD_RESPONSE = 'RESPONSE_ADD';
const ADD_ENDORSE = 'ENDORSE_ADD';
const REMOVE_ENDORSE = 'ENDORSE_REMOVE';
const RESPONSE_REMOVED = 'RESPONSE_REMOVED';
const ADD_FLAG = 'FLAG_ADD';
const REMOVE_FLAG = 'FLAG_REMOVE';

export default {
  QUESTION_ASKED,
  QUESTION_REMOVED,
  ADD_VOTE,
  REMOVE_VOTE,
  ADD_RESPONSE,
  RESPONSE_REMOVED,
  ADD_FLAG,
  REMOVE_FLAG,
  ADD_ENDORSE,
  REMOVE_ENDORSE,
}
