/**
 * @author Anthony Altieri on 11/15/16.
 */


// Questions
const QUESTION_ASKED = 'QUESTION_ASKED';
const QUESTION_REMOVED = 'QUESTION_REMOVED';
const ADD_VOTE = 'VOTE_ADD';
const REMOVE_VOTE = 'VOTE_REMOVE';
const ADD_RESPONSE = 'RESPONSE_ADD';
const ADD_ENDORSE = 'ENDORSE_ADD';
const REMOVE_ENDORSE = 'ENDORSE_REMOVE';
const RESPONSE_REMOVED = 'RESPONSE_REMOVED';
const ADD_FLAG = 'FLAG_ADD';
const REMOVE_FLAG = 'REMOVE_FLAG';
const ASSESSMENT_ACTIVATED = 'ASSESSMENT_ACTIVATED';
const ASSESSMENT_DEACTIVATED = 'ASSESSMENT_DEACTIVATED';
const INSTANT_ASSESSMENT_ANSWERED = 'INSTANT_ASSESSMENT_ANSWERED';
const REFLECTIVE_ASSESSMENT_REVIEWED = 'REFLECTIVE_ASSESSMENT_REVIEWED';
const REFLECTIVE_ASSESSMENT_ANSWERED = 'REFLECTIVE_ASSESSMENT_ANSWERED';
const REFLECTIVE_ASSESSMENT_START_REVIEW = 'REFLECTIVE_ASSESSMENT_START_REVIEW';
const STUDENT_JOINED_ATTENDANCE = 'STUDENT_JOINED_ATTENDANCE';

export default {
  QUESTION_ASKED,
  QUESTION_REMOVED,
  ADD_VOTE,
  REMOVE_VOTE,
  ADD_RESPONSE,
  RESPONSE_REMOVED,
  ADD_FLAG,
  REMOVE_FLAG,
  ADD_ENDORSE,
  REMOVE_ENDORSE,
  ASSESSMENT_ACTIVATED,
  ASSESSMENT_DEACTIVATED,
  INSTANT_ASSESSMENT_ANSWERED,
  REFLECTIVE_ASSESSMENT_REVIEWED,
  REFLECTIVE_ASSESSMENT_ANSWERED,
  REFLECTIVE_ASSESSMENT_START_REVIEW,
  STUDENT_JOINED_ATTENDANCE
}
