/**
 * @author Anthony Altieri on 11/15/16.
 */


// Questions
const QUESTION_ASKED = 'QUESTION_ASKED';
const QUESTION_REMOVED = 'QUESTION_REMOVED';
const ADD_VOTE = 'ADD_VOTE';
const REMOVE_VOTE = 'REMOVE_VOTE';
const ADD_RESPONSE = 'ADD_RESPONSE';
const ADD_ENDORSE = 'ADD_ENDORSE';
const REMOVE_ENDORSE = 'REMOVE_ENDORSE';
const REMOVE_RESPONSE = 'REMOVE_RESPONSE';
const ADD_FLAG = 'ADD_FLAG';
const REMOVE_FLAG = 'REMOVE_FLAG';

export default {
  QUESTION_ASKED,
  QUESTION_REMOVED,
  ADD_VOTE,
  REMOVE_VOTE,
  ADD_RESPONSE,
  REMOVE_RESPONSE,
  ADD_FLAG,
  REMOVE_FLAG,
  ADD_ENDORSE,
  REMOVE_ENDORSE,
}
